before_script:
  - gem install cutest
  - gem install hiredis

language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode

notifications:
  irc:
    - irc.freenode.net#redis-rb
  email:
    - damian.janowski@gmail.com
    - michel@soveran.com
    - pcnoordhuis@gmail.com
