language: ruby

script: make test

rvm:
  - 2.1
  - 2.2
  - 2.3
  - jruby-9
  - rbx-3

gemfile: ".travis/Gemfile"

sudo: false

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1
  matrix:
    - conn=ruby      REDIS_BRANCH=3.0
    - conn=ruby      REDIS_BRANCH=3.2
    - conn=hiredis   REDIS_BRANCH=3.0
    - conn=hiredis   REDIS_BRANCH=3.2
    - conn=synchrony REDIS_BRANCH=3.0
    - conn=synchrony REDIS_BRANCH=3.2
    - conn=ruby      REDIS_BRANCH=unstable

branches:
  only:
    - master

matrix:
  exclude:
    # hiredis
    - rvm: jruby-9
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=3.0
    - rvm: jruby-9
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=3.2
    - rvm: jruby-9
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=3.0
    - rvm: jruby-9
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=3.2

    # synchrony
    - rvm: jruby-9
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.0
    - rvm: jruby-9
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.2
    - rvm: jruby-9
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.0
    - rvm: jruby-9
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.2
  allow_failures:
    - rvm: rbx-3

notifications:
  irc:
    - irc.freenode.net#redis-rb
  email: false
